### ISSUE TITLE
Use without Compute Canada

### ISSUE THREAD

**Issue by DanBuchan** [ThomasDesc/NRGDock_public#1]
Hi,

Is it possible/trivial to get this running without using Compute Canada (as per the software guide provided)?
 
Thanks,
Daniel.

**Comment by ThomasDesc** [comment]
Hello, 

This repository was created mainly for a course on how to use an early demo version of NRGDock with Compute Canada. NRGDock has changed a lot since then. A standalone version will be released in the coming weeks once the preprint is available. Additionally, we are working on a PyMOL plugin that should be released soon.

Thomas

**Comment by DanBuchan** [comment]
Hi Thomas,

That's great. Really looking forward to using it!
